package com.santiago.battaglino.esp32.util

object Arguments {
    const val DISABLE_RECORD_VIDEO = "RECORD_VIDEO"
    const val DISABLE_AUTO_CONNECT_SHIMMER = "AUTO_CONNECT_SHIMMER"
    const val ENABLE_DELETE_REMOTE_SESSIONS = "DELETE_REMOTE_SESSION"
    const val DESIRED_BUCKETS = "DESIRED_BUCKETS"
    const val START_DESTINATION = "START_DESTINATION"
    const val SESSION_ID = "SESSION_ID"
    const val SERVER_IP_ADDRESS = "SERVER_IP_ADDRESS"
    const val SHIMMER_MAC_ADDRESS = "SHIMMER_MAC_ADDRESS"
}